---
- hosts: all
  tasks: 
    - set_fact:
        key_value: release_dir="/var/rails/canvas/releases/{{ release_name }}"

- name: Create release directory
  hosts: all
  tasks:
    - file:
        path: "{{ release_dir }}"
        state: directory
  
- name: Extract release tarball to release directory
  hosts: all
  tasks:
    - unarchive:
        src: "/usr/local/canvas/deploy-release-{{ canvas_env }}/{{ release_name }}/canvas.tar"
        dest: "{{ release_dir }}"

- name: Copy config files from templates
  hosts: all
  tasks:
    - shell: "/usr/local/canvas/bin/canvasconfig -r {{ release_name }}"

- name: Symlink canvas data mount
  hosts: all
  tasks:
    - file:
        path: "{{ release_dir }}/mnt/data"
        state: directory
    - file:
        path: "{{ release_dir }}/mnt/data/canvasfiles"
        src: /mnt/data/canvasfiles
        state: link

- name: Rebuild brand configs and copy
  hosts: management
  tasks:
    - shell: bundle exec rake brand_configs:generate_and_upload_all
      when: primary_management == true
      args:
        chdir: "{{ release_dir }}"
      environment:
        RAILS_ENV: production
    - copy:
        when: primary_management == true
        src: "{{ release_dir }}/public/dist/brandable_css"
        dest: "/mnt/data/brandable_css/{{ release_name }}"
        remote_src: yes

- name: Symlink brandable CSS
  hosts: all
  tasks:
    - file:
        path: "{{ release_dir }}/public/dist/brandable_css"
        state: absent
    - file:
        name: "{{ release_dir }}/public/dist/brandable_css"
        src: "/mnt/data/brandable_css/{{ release_name }}"
        state: link

- name: Run predeploy migrations
  hosts: management
  tasks:
    - shell: bundle exec rake db:migrate:predeploy
      when: primary_management == true
      args:
        chdir: "{{ release_dir }}"
      environment:
        RAILS_ENV: production

- name: Move current symlink
  hosts: all
  tasks:
    - file:
        path: /var/rails/canvas/current
        state: absent
    - file:
        path: /var/rails/canvas/current
        src: "{{ release_dir }}"
        state: link

- name: Restart jobs processors
  hosts: management
  tasks:
    - service:
      name: canvas-jobs
      state: restarted

- name: Restart app processes
  hosts: all
  tasks:
    - shell: "passenger-config restart-app --rolling-restart /var/rails/canvas/current"

