- name: Add nodesource
  sudo: yes
  shell: curl -sL https://deb.nodesource.com/setup | bash -

- name: Install python-software-properties
  sudo: yes
  apt: pkg=python-software-properties state=installed

- name: Add brightbox ppa
  sudo: yes
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: Update apt cache
  sudo: yes
  apt: update_cache=yes

- name: Install dependencies
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - zlib1g-dev
    - libxml2-dev
    - libmysqlclient-dev
    - libxslt1-dev
    - libsqlite3-dev
    - imagemagick
    - libpq-dev
    - libxmlsec1-dev
    - libcurl4-gnutls-dev
    - libxmlsec1
    - build-essential
    - openjdk-7-jre
    - unzip
    - nodejs
    - git
    - ruby2.1
    - ruby2.1-dev
    - redis-server

- name: Remove ruby 2.0
  sudo: yes
  apt: pkg=ruby2.0 state=absent

- name: Update npm to latest
  sudo: yes
  shell: npm -g install npm
